name: HIStudy SSH Command CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
