name: HIStudy SSH Command CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    name: Deploy
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Run a one-line script
        run: |
          nohup bash -c "/home/histudy/deploy.sh > /home/histudy/deploy.log 2>&1 &" && disown
