name: HIStudy SSH Command CD
on:
   push:
      tags:
         - v*
   workflow_dispatch:

jobs:
   build:
      name: Deploy
      runs-on: [self-hosted, Linux, X64]
      steps:
         - name: Run a one-line script
           run: |
              /home/histudy/deploy.runner.sh
